[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
  set helplang=ja
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  colorscheme gruvbox
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
  \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
  \ <bang>0)
  nnoremap <C-p> :Files<CR>
  nnoremap <C-h> :History<CR>
  nnoremap <leader>: :History:<CR>
  command C :Files ~/.config/nvim
'''

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  " f{char} to move to {char}
  map <leader>f <Plug>(easymotion-bd-f)
  nmap <leader>f <Plug>(easymotion-overwin-f)
  " f{char}{char} to move to {char}{char}
  map <leader><leader>f <Plug>(easymotion-bd-f2)
  nmap <leader><leader>f <Plug>(easymotion-overwin-f2)
  " Move to line
  map <leader>l <Plug>(easymotion-bd-jk)
  nmap <leader>l <Plug>(easymotion-overwin-line)
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
lua << EOF
  require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    "go",
    "python",
    "javascript",
    "typescript",
    "bash",
    "vim",
    "markdown",
    "json",
    "yaml",
    "toml",
    "lua",
  },
  auto_install = true,
  ignore_install = { },
  highlight = {
    enable = true,
  },
}
EOF
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
  let g:table_mode_corner='|'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \   'deno' : {
  \     'command': 'deno',
  \     'cmdopt': '--no-check --allow-all --unstable',
  \     'exec': ['%c run %o %s'],
  \   },
  \   'bash' : {
  \     'command': 'bash',
  \     'exec': ['%c %s'],
  \   },
  \   'go' : {
  \     'command': 'go',
  \     'exec': ['%c run %s'],
  \   }
  \ }
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled=1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  "let g:airline_powerline_fonts = 1
  let g:airline_theme='base16_gruvbox_dark_hard'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
