[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add ='''
lua << EOF
  local on_attach = function(client, bufnr)
    -- Enable completion triggered by <c-x><c-o>
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local bufopts = { noremap=true, silent=true, buffer=bufnr }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
    vim.keymap.set('n', '<space>k', vim.lsp.buf.signature_help, bufopts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, bufopts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, bufopts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, bufopts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, bufopts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, bufopts)
    vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, bufopts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
    vim.keymap.set('n', '<C-l>f', vim.lsp.buf.format, bufopts)
  end

  require('mason').setup()
  require("mason-lspconfig").setup()
  require("mason-lspconfig").setup_handlers {
    function (server_name) -- default handler (optional)
      -- conflict lsp. autostart ng.
      -- check cmd LspInfo.
      conflict_list = {'denols'}
      for i = 1 , #conflict_list do
        if conflict_list[i] == server_name then
          require("lspconfig")[server_name].setup {
            autostart = false,
            on_attach = on_attach
          }
          return
        end
      end

      require("lspconfig")[server_name].setup {
        on_attach = on_attach
      }
    end,
  }
EOF
'''

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['mason.nvim']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason.nvim']
